services:
  postgres:
    container_name: timemanagement_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "time_management"
      POSTGRES_USER: "hollyjudge"
      POSTGRES_PASSWORD: "vernonburg2025"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - inethi-bridge-traefik
      - timemanagement_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timemanagement_django
    environment:
      - DATABASE_URL=postgres://hollyjudge:vernonburg2025@postgres:5432/time_management
    depends_on:
      - postgres
    volumes:
      - .:/app 
    networks:
      - inethi-bridge-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.timesheets.rule=Host(`timesheets.costbroadband.net`)"
      - "traefik.http.routers.timesheets.entrypoints=websecure"
      - "traefik.http.services.timesheets.loadbalancer.server.port=8000"
      - "traefik.http.routers.timesheets.tls=true"

networks:
  timemanagement_network:
    driver: bridge
  inethi-bridge-traefik:
    external:
      name: "inethi-bridge-traefik"

volumes:
  db_data:

