# Generated by Django 4.2.18 on 2025-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='task_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
