# Generated by Django 5.1.3 on 2025-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0002_rename_dailyworkhour_timesheetentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
